### ISSUE TITLE
ComputerName Pattern correction

### ISSUE THREAD

**Issue by AlWilliamsFlorida** [davidhaymond/ProvisioningTools#4]
I can create the Computer name "TEST-A-%RAND:4%" within the ICD.exe GUI as a computer name format. This pattern is not accepted by New-ProvisioningPackage.

1. Run Command: New-ProvisioningPackage -Computername 'TEST-A-%RAND:4%'

**Expected behavior**

This computer name format works fine in ICD.exe.

<img width="758" alt="Annotation 2020-08-26 164926" src="https://user-images.githubusercontent.com/70290993/91355422-1f1bb980-e7bc-11ea-8cc9-b266a2776e22.png">

**Comment by davidhaymond** [comment]
@AlWilliamsFlorida Thanks so much for the bug report! I've pushed a fix (v1.2.3) to the PowerShell Gallery.
